apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
    version: {{ .Values.backend.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
